### ISSUE TITLE
Streamline use of .ENV and /root/.env

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/seccheck#10]
**Is your feature request related to a problem? Please describe.**

.ENV repeats much of what we already put into /root/.env

**Describe the solution you'd like**

.ENV should source /root/.env (and from there generally there should be no need to edit)

**Describe alternatives you've considered**

We could combine seccheck .ENV into /root/.env (or minimise use of .ENV to what can be found in /root/.env)

**Comment by kumarnarendra701** [comment]
@cpswan - Modified seccheck script to use root env. Please verify the below PR and let me know if you see any changes.

https://github.com/atsign-foundation/seccheck/pull/20

**Comment by cpswan** [comment]
That PR needs some work. This can be closed once it's approved and merged.

**Comment by kumarnarendra701** [comment]
@cpswan - I made all changes to the copy of the staging script(/home/cconstab/seccheck) and then copied all files in my branch and it overwrite all files. So I have fixed overwrite issue.

**Comment by cpswan** [comment]
Approved and merged.
