### ISSUE TITLE
Script to report how many days since last run of certificate renewals

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/seccheck#22]
### Is your feature request related to a problem? Please describe.

Lock files get stuck, and this is often only caught by reports of certificates about to expire

### Describe the solution you'd like

Augment the daily reports for secondary versions with a report of when cert renewal last ran.

### Describe alternatives you've considered

We could also have a script that compares the state of the lock file to the process table of the machine holding the lock to verify that there is an active process holding the lock.

**Comment by cpswan** [comment]
I'm presently seeing reports like this on the Production Monitoring channel:

```
SSl Renewal Status : 
 Warning - Certs Renewal process last ran was 1 days ago for canary
Warning - Certs Renewal process last ran was 6 hours ago for swarm0003
Warning - Certs Renewal process last ran was 6 hours ago for swarm0001
Warning - Certs Renewal process last ran was 5 hours ago for swarm0004
Warning - Certs Renewal process last ran was 4 hours ago for swarm0002 
```

Things I'd like to change:

* Only say 'Warning' if there's a problem (that the job hasn't run for a few days)
* s/last ran/last run/
* If there's a run in progress say how long it's been running (which could be days for cases where cert renewals have clumped together on swarm0001 and swarm0002), and when that last cert update happened (which should be at most a few minutes ago).
* Although it's not production, I think the staging certs renewal should be included here, as that can also hold the lock (even if it's just to say that staging holds the lock, and how long it's been held for, because getting at the staging logs from prod will be tricky).

I'll keep 3SP against this and move to PR53 so the items above can be addressed.

**Comment by kumarnarendra701** [comment]
@cpswan - Please review the below PR's.
https://github.com/atsign-company/secondaries-scripts/pull/63

https://github.com/atsign-foundation/seccheck/pull/23

**Comment by kumarnarendra701** [comment]
@cpswan - All the above points have been covered except staging because we have different NFS servers in staging and cannot share lock files between prod and stage renewal scripts together. So we have a different script running on stage to handle the lock. Please let me know if you need any further changes.

**Comment by cpswan** [comment]
@kumarnarendra701 I'd still like to get staging into the reports. Can't we use the GCS bucket to pass info between the environments? I also wonder if we could use DNS TXT records (or similar) as a way to keep track?

**Comment by kumarnarendra701** [comment]
@cpswan  - Working on integration GCS bucket for stage and prod. so moving this to PR54

**Comment by kumarnarendra701** [comment]
@cpswan - Modified script to add Staging SSL renewal status in gChat notification.

https://github.com/atsign-foundation/seccheck/pull/25

https://github.com/atsign-company/secondaries-scripts/pull/64
