### ISSUE TITLE
Include registry cert in periodic certificate checks

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/seccheck#24]
### Is your feature request related to a problem? Please describe.

https://github.com/atsign-foundation/at_server/issues/1136

### Describe the solution you'd like

When we check certs, also check the cert on the running registry service (not just the filesystem) to ensure it's not about to expire.

**Comment by kumarnarendra701** [comment]
@cpswan - Added reg SSL check in cert alert.

https://github.com/atsign-foundation/seccheck/pull/26

**Comment by kumarnarendra701** [comment]
@cpswan - Can we close this ticket or let me know if need any other modifications?
