### ISSUE TITLE
Alerts for memory utilization of secondaries

### ISSUE THREAD

**Issue by kumarnarendra701** [atsign-foundation/seccheck#28]
Create a script to monitor the memory utilization of secondaries.

**Comment by kumarnarendra701** [comment]
@cpswan - This ticket is to get the memory utilization alerts of secondaries and report them to Gchat. So that we can take action and fix the secondary failure issue.

To monitor the memory utilization of secondary containers in your Docker Swarm cluster, I found a way to obtain memory utilization information from the worker nodes where the containers are running using the "docker stats" command. However, this approach requires adding a script to a cronjob on every worker node to receive alerts when the memory usage exceeds a certain threshold.

Although I tried to obtain memory utilization details from the Docker stacks/services level but did not get any success with this approach.

Please let me know if you have any thoughts.

**Comment by cpswan** [comment]
@kumarnarendra701 (and @athandle) before we go too far down this road I'd like to have a discussion in an arch call (once I'm back next week).

**Comment by athandle** [comment]
no scripts to run on worker node
we need to track why we need more memory - https://github.com/atsign-foundation/at_server/issues/1303
linked
https://github.com/atsign-foundation/operations/issues/345

**Comment by cpswan** [comment]
Closing this ticket, as whatever we do about this problem, it won't be using the seccheck approach.
