### ISSUE TITLE
Seccheck reports count from initial scan rather than double check

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/seccheck#5]
**Describe the bug**

Occasionally there are reports like this:

```
3 Problematic Secondaries 
Of the 3 these are the first few effected @signs,  @forestgreenquerulous1 (3000), 
```

Clearly there were 3 problematic secondaries on the first check, but only one on the double check.

**Expected behavior**

Only the number of failures from the double check should be reported.

**Comment by cconstab** [comment]
Checked and closed
